import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  teams: [
    {
      id: 13,
      value: 0,
      name: "E1",
      border_color: "#ffaaff",
      currentList: "roster",
    },
    {
      id: 14,
      name: "M1",
      border_color: "#ffaaff",
      value: 1,
      currentList: "roster",
    },
    {
      id: 15,
      name: "A1",
      border_color: "#ffaaff",
      value: 2,
      currentList: "roster",
    },
    {
      id: 13,
      value: 0,
      name: "A21",
      border_color: "#ffaaff",
      currentList: "roster",
    },
    {
      id: 14,
      name: "E21",
      border_color: "#ffaaff",
      value: 1,
      currentList: "roster",
    },
    {
      id: 15,
      name: "T21",
      border_color: "#ffaaff",
      value: 2,
      currentList: "roster",
    },
    {
      id: 16,
      name: "M21",
      border_color: "#ffaaff",
      value: 3,
      currentList: "roster",
    },
    {
      id: 17,
      name: "F201",
      border_color: "#ffaaff",
      value: 4,
      currentList: "roster",
    },
    {
      id: 18,
      name: "F202",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },

    {
      id: 13,
      value: 0,
      name: "E31",
      border_color: "#ffaaff",
      currentList: "roster",
    },
    {
      id: 14,
      name: "E32",
      border_color: "#ffaaff",
      value: 1,
      currentList: "roster",
    },
    {
      id: 15,
      name: "T31",
      border_color: "#ffaaff",
      value: 2,
      currentList: "roster",
    },
    {
      id: 13,
      value: 0,
      name: "A31",
      border_color: "#ffaaff",
      currentList: "roster",
    },
    {
      id: 14,
      name: "A32",
      border_color: "#ffaaff",
      value: 1,
      currentList: "roster",
    },
    {
      id: 15,
      name: "M31",
      border_color: "#ffaaff",
      value: 2,
      currentList: "roster",
    },
    {
      id: 16,
      name: "BC31",
      border_color: "#ffaaff",
      value: 3,
      currentList: "roster",
    },
    {
      id: 17,
      name: "F301",
      border_color: "#ffaaff",
      value: 4,
      currentList: "roster",
    },
    {
      id: 18,
      name: "F302",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "F313",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 15,
      name: "A41",
      border_color: "#ffaaff",
      value: 2,
      currentList: "roster",
    },
    {
      id: 13,
      value: 0,
      name: "A42",
      border_color: "#ffaaff",
      currentList: "roster",
    },
    {
      id: 14,
      name: "E41",
      border_color: "#ffaaff",
      value: 1,
      currentList: "roster",
    },
    {
      id: 15,
      name: "E42",
      border_color: "#ffaaff",
      value: 2,
      currentList: "roster",
    },
    {
      id: 16,
      name: "T42",
      border_color: "#ffaaff",
      value: 3,
      currentList: "roster",
    },
    {
      id: 17,
      name: "M42",
      border_color: "#ffaaff",
      value: 4,
      currentList: "roster",
    },
    {
      id: 18,
      name: "F401",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "F402",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 13,
      value: 0,
      name: "A51",
      border_color: "#ffaaff",
      currentList: "roster",
    },
    {
      id: 14,
      name: "A52",
      border_color: "#ffaaff",
      value: 1,
      currentList: "roster",
    },
    {
      id: 15,
      name: "A53",
      border_color: "#ffaaff",
      value: 2,
      currentList: "roster",
    },
    {
      id: 16,
      name: "A54",
      border_color: "#ffaaff",
      value: 3,
      currentList: "roster",
    },
    {
      id: 17,
      name: "ME51",
      border_color: "#ffaaff",
      value: 4,
      currentList: "roster",
    },
    {
      id: 18,
      name: "ME52",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "ME53",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "E54",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "BC51",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 17,
      name: "E61",
      border_color: "#ffaaff",
      value: 4,
      currentList: "roster",
    },
    {
      id: 18,
      name: "T61",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "A61",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "M61",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "F601",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "E71",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 17,
      name: "T71",
      border_color: "#ffaaff",
      value: 4,
      currentList: "roster",
    },
    {
      id: 18,
      name: "A71",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "M71",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "F701",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "T101",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
    {
      id: 18,
      name: "BC111",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
    },
  ],
};

const rosterTeamsSlice = createSlice({
  name: "rosterTeams",
  initialState,
  reducers: {
    spliceRoster: (state, action) => {
      state.teams.splice(action.payload, 1);
    },
    pushRoster: {
      reducer: (state, action) => {
        state.teams.push(action.payload);
      },
      prepare: (value) => {
        return {
          payload: {
            ...value,
            currentList: "roster",
          },
        };
      },
    },
  },
});

export const {spliceRoster, pushRoster } = rosterTeamsSlice.actions;

export default rosterTeamsSlice.reducer;
