import { createSlice } from "@reduxjs/toolkit";

const customTeam = {
  teamName: "Custom",
  teams: [
    {
      id: 101,
      name: "T21",
      border_color: "#ffaaff",
      value: 2,
      currentList: "roster",
      department: 0,
    },
    {
      id: 102,
      value: 0,
      name: "E31",
      border_color: "#ffaaff",
      currentList: "roster",
      department: 0,
    },
    {
      id: 103,
      name: "E32",
      border_color: "#ffaaff",
      value: 1,
      currentList: "roster",
      department: 0,
    },
    {
      id: 104,
      name: "T31",
      border_color: "#ffaaff",
      value: 2,
      currentList: "roster",
      department: 0,
    },
    {
      id: 105,
      value: 0,
      name: "A31",
      border_color: "#ffaaff",
      currentList: "roster",
      department: 0,
    },
    {
      id: 106,
      name: "M31",
      border_color: "#ffaaff",
      value: 2,
      currentList: "roster",
      department: 0,
    },
    {
      id: 107,
      name: "F302",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
      department: 0,
    },
    {
      id: 108,
      name: "F313",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
      department: 0,
    },
    {
      id: 109,
      name: "E42",
      border_color: "#ffaaff",
      value: 2,
      currentList: "roster",
      department: 0,
    },
    {
      id: 110,
      name: "BC41",
      border_color: "#ffaaff",
      value: 2,
      currentList: "roster",
      department: 0,
    },
    {
      id: 32,
      name: "ME51",
      border_color: "#ffaaff",
      value: 4,
      currentList: "roster",
      department: 0,
    },
    {
      id: 36,
      name: "BC51",
      border_color: "#ffaaff",
      value: 5,
      currentList: "roster",
      department: 0,
    },
  ],
};

const initialState = {
  roster: [
    customTeam,
    {
      teamName: "South Weber",
      teams: [
        {
          id: 1,
          value: 0,
          name: "E1",
          border_color: "#ffaaff",
          currentList: "roster",
          department: 1,
        },
        {
          id: 2,
          name: "M1",
          border_color: "#ffaaff",
          value: 1,
          currentList: "roster",
          department: 1,
        },
        {
          id: 3,
          name: "A1",
          border_color: "#ffaaff",
          value: 2,
          currentList: "roster",
          department: 1,
        },
      ],
    },
    {
      teamName: "Clinton",
      teams: [
        {
          id: 4,
          value: 0,
          name: "A21",
          border_color: "#ffaaff",
          currentList: "roster",
          department: 2,
        },
        {
          id: 5,
          name: "E21",
          border_color: "#ffaaff",
          value: 1,
          currentList: "roster",
          department: 2,
        },
        {
          id: 6,
          name: "T21",
          border_color: "#ffaaff",
          value: 2,
          currentList: "roster",
          department: 2,
        },
        {
          id: 7,
          name: "M21",
          border_color: "#ffaaff",
          value: 3,
          currentList: "roster",
          department: 2,
        },
        {
          id: 8,
          name: "F201",
          border_color: "#ffaaff",
          value: 4,
          currentList: "roster",
          department: 2,
        },
        {
          id: 9,
          name: "F202",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 2,
        },
      ],
    },
    {
      teamName: "Syracuse",
      teams: [
        {
          id: 10,
          value: 0,
          name: "E31",
          border_color: "#ffaaff",
          currentList: "roster",
          department: 3,
        },
        {
          id: 11,
          name: "E32",
          border_color: "#ffaaff",
          value: 1,
          currentList: "roster",
          department: 3,
        },
        {
          id: 12,
          name: "T31",
          border_color: "#ffaaff",
          value: 2,
          currentList: "roster",
          department: 3,
        },
        {
          id: 13,
          value: 0,
          name: "A31",
          border_color: "#ffaaff",
          currentList: "roster",
          department: 3,
        },
        {
          id: 14,
          name: "A32",
          border_color: "#ffaaff",
          value: 1,
          currentList: "roster",
          department: 3,
        },
        {
          id: 15,
          name: "M31",
          border_color: "#ffaaff",
          value: 2,
          currentList: "roster",
          department: 3,
        },
        {
          id: 16,
          name: "BC31",
          border_color: "#ffaaff",
          value: 3,
          currentList: "roster",
          department: 3,
        },
        {
          id: 17,
          name: "F301",
          border_color: "#ffaaff",
          value: 4,
          currentList: "roster",
          department: 3,
        },
        {
          id: 18,
          name: "F302",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 3,
        },
        {
          id: 19,
          name: "F313",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 3,
        },
      ],
    },
    {
      teamName: "North Davis",
      teams: [
        {
          id: 20,
          name: "A41",
          border_color: "#ffaaff",
          value: 2,
          currentList: "roster",
          department: 4,
        },
        {
          id: 21,
          value: 0,
          name: "A42",
          border_color: "#ffaaff",
          currentList: "roster",
          department: 4,
        },
        {
          id: 22,
          name: "E41",
          border_color: "#ffaaff",
          value: 1,
          currentList: "roster",
          department: 4,
        },
        {
          id: 23,
          name: "E42",
          border_color: "#ffaaff",
          value: 2,
          currentList: "roster",
          department: 4,
        },
        {
          id: 24,
          name: "T42",
          border_color: "#ffaaff",
          value: 3,
          currentList: "roster",
          department: 4,
        },
        {
          id: 25,
          name: "M42",
          border_color: "#ffaaff",
          value: 4,
          currentList: "roster",
          department: 4,
        },
        {
          id: 26,
          name: "F401",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 4,
        },
        {
          id: 27,
          name: "F402",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 4,
        },
      ],
    },
    {
      teamName: "Layton",
      teams: [
        {
          id: 28,
          value: 0,
          name: "A51",
          border_color: "#ffaaff",
          currentList: "roster",
          department: 5,
        },
        {
          id: 29,
          name: "A52",
          border_color: "#ffaaff",
          value: 1,
          currentList: "roster",
          department: 5,
        },
        {
          id: 30,
          name: "A53",
          border_color: "#ffaaff",
          value: 2,
          currentList: "roster",
          department: 5,
        },
        {
          id: 31,
          name: "A54",
          border_color: "#ffaaff",
          value: 3,
          currentList: "roster",
          department: 5,
        },
        {
          id: 32,
          name: "ME51",
          border_color: "#ffaaff",
          value: 4,
          currentList: "roster",
          department: 5,
        },
        {
          id: 33,
          name: "ME52",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 5,
        },
        {
          id: 34,
          name: "ME53",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 5,
        },
        {
          id: 35,
          name: "E54",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 5,
        },
        {
          id: 36,
          name: "BC51",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 5,
        },
      ],
    },
    {
      teamName: "Kaysville",
      teams: [
        {
          id: 37,
          name: "E61",
          border_color: "#ffaaff",
          value: 4,
          currentList: "roster",
          department: 6,
        },
        {
          id: 38,
          name: "T61",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 6,
        },
        {
          id: 39,
          name: "A61",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 6,
        },
        {
          id: 40,
          name: "M61",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 6,
        },
        {
          id: 41,
          name: "F601",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 6,
        },
      ],
    },
    {
      teamName: "Farmington",
      teams: [
        {
          id: 42,
          name: "E71",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 7,
        },
        {
          id: 43,
          name: "T71",
          border_color: "#ffaaff",
          value: 4,
          currentList: "roster",
          department: 7,
        },
        {
          id: 44,
          name: "A71",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 7,
        },
        {
          id: 45,
          name: "M71",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 7,
        },
        {
          id: 46,
          name: "F701",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 7,
        },
      ],
    },
    {
      teamName: "Hill AFB",
      teams: [
        {
          id: 47,
          name: "T101",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 8,
        },
        {
          id: 48,
          name: "BC111",
          border_color: "#ffaaff",
          value: 5,
          currentList: "roster",
          department: 8,
        },
      ],
    },
  ],
};

const rosterTeamsSlice = createSlice({
  name: "rosterTeams",
  initialState,
  reducers: {
    spliceRoster: (state, action) => {
      state.roster[action.payload.item.department].teams.splice(
        action.payload.index,
        1
      );
    },
    insertRoster: {
      reducer: (state, action) => {
        state.roster[action.payload.item.department].teams.push(
          action.payload.item
        );
      },
      prepare: (value) => {
        return {
          payload: {
            ...value,
            item: {
              ...value.item,
              currentList: "roster",
            },
          },
        };
      },
    },
  },
});

export const { spliceRoster, insertRoster } = rosterTeamsSlice.actions;

export default rosterTeamsSlice.reducer;
